import type { Metadata } from "next";
import { ArrowRight, ExternalLink, Plus } from "lucide-react";
import { ReactionTest } from "@/components/reaction-test";

const pageUrl = "https://reaction-test.org/reflex-test/";

export const metadata: Metadata = {
  title: "Reflex Test - How Fast Are Your Reflexes?",
  description: "Test your reflexes for free. See how fast you react to visual stimuli and compare your reflex speed with the average.",
  alternates: { canonical: pageUrl },
  openGraph: { title: "Reflex Test - How Fast Are Your Reflexes?", description: "A free five-round reflex test for measuring visual response speed.", url: pageUrl, siteName: "Reaction Time", type: "website", locale: "en_US", images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "Reflex test score screen" }] },
  twitter: { card: "summary_large_image", title: "Reflex Test - How Fast Are Your Reflexes?", description: "Measure your reflex speed in five quick rounds.", images: ["/og-image.png"] }
};

const faqItems = [
  ["What is a reflex test?", "A reflex test is a timed task that presents a signal and measures how quickly you make a response. This page uses a simple visual signal: wait for green, then click or tap."],
  ["What is a good reflex speed?", "A repeatable result around 200 to 300 milliseconds is a practical browser-test range for many adults. The exact score depends on the display, input device, browser, attention, and test design."],
  ["Is a reflex the same as reaction time?", "They are related but not identical. A reflex is an automatic response mediated by a reflex pathway, while a reaction-time task usually involves noticing a signal and deliberately choosing a response. Online reflex testers mostly measure simple reaction time."],
  ["Can I use this reflex tester on my phone?", "Yes. Tap the test surface after it turns green. A phone may add different touchscreen and display latency, so compare mobile sessions with other sessions on the same phone."],
  ["Why did I get a different reflex score each time?", "Variation is normal. The waiting delay changes, your attention shifts, and browser or device timing is not perfectly identical. Five valid rounds give a more useful average than one click."],
  ["How can I improve my reflexes?", "Practice short sessions, sleep consistently, reduce distractions, and keep your eyes on the signal area. Training can improve familiarity and consistency, but this simple test cannot measure every skill used in sport or gaming."]
] as const;

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebApplication", "@id": `${pageUrl}#app`, name: "Reflex Test", url: pageUrl, description: metadata.description, applicationCategory: "GameApplication", applicationSubCategory: "Reflex Tester", operatingSystem: "Any", browserRequirements: "JavaScript enabled", isAccessibleForFree: true, offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } },
    { "@type": "FAQPage", "@id": `${pageUrl}#faq`, url: pageUrl, mainEntity: faqItems.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Reaction Time Test", item: "https://reaction-test.org/" }, { "@type": "ListItem", position: 2, name: "Reflex Test", item: pageUrl }] }
  ]
};

export default function ReflexTestPage() {
  return (
    <>
      <a href="#main" className="fixed left-3 top-3 z-50 -translate-y-24 rounded bg-marker px-4 py-2 font-bold text-ink transition-transform focus:translate-y-0">Skip to reflex test</a>
      <header className="border-b border-line bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><a href="/" className="flex items-center gap-2 no-underline" aria-label="Reaction Time home"><span className="grid h-8 w-8 place-items-center rounded bg-ink text-xs font-black text-marker">RT</span><span className="text-sm font-black uppercase">Reaction Time</span></a><nav aria-label="Primary navigation" className="flex items-center gap-5 text-xs font-bold text-slate-600 sm:gap-7"><a href="/" className="hover:text-action">Reaction time test</a><a href="/average-reaction-time/" className="hidden hover:text-action sm:inline">Average time</a><a href="#faq" className="hover:text-action">FAQ</a></nav></div></header>
      <main id="main"><article>
        <header className="timing-grid border-b border-line px-4 py-12 sm:px-6 sm:py-16"><div className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="text-xs font-bold text-slate-500"><a href="/" className="hover:text-action">Reaction Time Test</a><span aria-hidden="true" className="mx-2">/</span><span>Reflex Test</span></nav><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_300px] lg:items-end"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.1em] text-action">Visual reflex tester · five valid rounds</p><h1 className="mt-4 text-4xl font-black leading-[1.05] sm:text-5xl lg:text-6xl">Reflex Test</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-700"><strong className="text-ink">How fast are your reflexes?</strong> Take this free reflex test, wait for the screen to turn green, and respond as quickly as you can. Five valid attempts show your average and best visual response in milliseconds.</p></div><aside className="border-l-4 border-marker bg-white p-6" aria-label="Test format"><p className="text-xs font-black uppercase text-slate-500">Test format</p><p className="data-number mt-3 text-5xl font-black">5<span className="ml-1 text-lg">rounds</span></p><p className="mt-3 text-sm leading-6 text-slate-600">Random wait, false-start protection, and a five-round average.</p></aside></div></div></header>

        <section id="test" className="copy-section scroll-mt-6 border-b border-line bg-white py-12 sm:py-16"><div className="mx-auto max-w-5xl px-4 sm:px-6"><ReactionTest label="Reflex lab" completionLabel="reflex speed" ariaLabel="Reflex test" /><p className="mx-auto mt-5 max-w-3xl text-center text-xs leading-5 text-slate-500">The result includes display, browser, and input-device latency. Use the same setup when comparing sessions.</p></div></section>

        <section className="copy-section border-b border-line bg-paper py-16 sm:py-24"><div className="mx-auto max-w-4xl px-4 sm:px-6"><p className="text-xs font-black uppercase tracking-[0.1em] text-action">The measurement</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">What Is a Reflex Test?</h2><p className="mt-5 leading-7 text-slate-600">A reflex test is a quick way to measure the time between a visible signal and your response. In this reflex tester, the signal is a green screen and your response is a click, tap, or keyboard activation. The browser reports elapsed time in milliseconds, so a smaller number means a faster response.</p><p className="mt-4 leading-7 text-slate-600">The everyday phrase “reflex speed” is useful, but this is not a clinical reflex examination. A true spinal reflex can happen automatically without conscious decision-making. An online test asks you to notice the signal, decide to respond, and move a finger or hand. That makes it a simple visual <a href="/" className="font-bold text-action">reaction time test</a>, with a reflex-themed goal.</p><p className="mt-4 leading-7 text-slate-600">Because the screen and device are part of the timing chain, repeatability matters. Keep your browser, display, input method, and posture consistent. A five-round average is more informative than a single lucky click.</p></div></section>

        <section className="copy-section border-b border-line bg-white py-16 sm:py-24"><div className="mx-auto grid max-w-6xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20"><div><p className="text-xs font-black uppercase tracking-[0.1em] text-action">Interpretation</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">What&apos;s a Good Reflex Speed?</h2><p className="mt-5 leading-7 text-slate-600">There is no universal cutoff because reflex tests use different signals and hardware. As practical online guidance, a consistent average near 200 ms is fast for many visual tasks, 220–280 ms is common, and slower scores deserve a calm retest rather than a judgment.</p><p className="mt-4 leading-7 text-slate-600">A score under 180 ms can be genuine, but it can also reflect anticipation. Wait for the color change every time and review all five rounds. Compare with our research-based <a href="/average-reaction-time/" className="font-bold text-action">average reaction time guide</a> for context, not as a diagnosis.</p></div><div className="min-w-0"><div className="overflow-x-auto border-y border-line"><table className="w-full min-w-[520px] border-collapse text-left text-sm"><caption className="sr-only">Practical reflex speed bands for a browser test</caption><thead><tr className="bg-paper text-xs uppercase text-slate-500"><th scope="col" className="px-4 py-3">Average</th><th scope="col" className="px-4 py-3">Practical band</th><th scope="col" className="px-4 py-3">How to read it</th></tr></thead><tbody className="divide-y divide-line"><tr><th scope="row" className="data-number px-4 py-4">Under 180 ms</th><td className="px-4 py-4 font-bold">Very fast</td><td className="px-4 py-4 text-slate-600">Repeat and rule out anticipation.</td></tr><tr><th scope="row" className="data-number px-4 py-4">180–219 ms</th><td className="px-4 py-4 font-bold">Fast</td><td className="px-4 py-4 text-slate-600">Quick visual response on many setups.</td></tr><tr><th scope="row" className="data-number px-4 py-4">220–279 ms</th><td className="px-4 py-4 font-bold">Common</td><td className="px-4 py-4 text-slate-600">A typical online comparison range.</td></tr><tr><th scope="row" className="data-number px-4 py-4">280 ms or more</th><td className="px-4 py-4 font-bold">Retest</td><td className="px-4 py-4 text-slate-600">Check rest, focus, and device delay.</td></tr></tbody></table></div><p className="mt-4 text-xs leading-5 text-slate-500">These are practical browser-test bands, not clinical norms or a test of neurological health.</p></div></div></section>

        <section className="copy-section border-b border-line bg-paper py-16 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-2 lg:gap-20"><div><h2 className="text-3xl font-black sm:text-4xl">Reflex Test vs. Reaction Time Test</h2><p className="mt-5 leading-7 text-slate-600">The terms overlap online. Both tasks can measure a response to a signal, but “reflex” often suggests an automatic response while “reaction time” describes the measurable interval. Our test needs conscious visual detection and movement, so reaction time is the more precise technical description.</p><p className="mt-4 leading-7 text-slate-600">A simple task has one signal and one response. A choice task might show different colors that require different keys. Choice reaction time is usually slower because identification and selection add steps. Do not compare a reflex score from this page with a choice task or a sports drill as if they were the same test.</p></div><div><h2 className="text-3xl font-black sm:text-4xl">How to Improve Your Reflexes</h2><p className="mt-5 leading-7 text-slate-600">Use short, repeatable practice rather than chasing a record for dozens of rounds. Take two or three five-round sessions, then stop. Sleep, regular physical activity, hydration, and a quiet testing environment support attention and motor control. The companion guide explains <a href="/how-to-increase-reaction-time/" className="font-bold text-action">how to increase reaction time</a> with practical drills.</p><p className="mt-4 leading-7 text-slate-600">Practice may make you more familiar with the task and more consistent. It does not remove monitor latency or guarantee faster performance in every game, sport, or driving situation.</p></div></div></div></section>

        <section className="copy-section border-b border-line bg-white py-16 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="text-xs font-black uppercase tracking-[0.1em] text-action">Run a valid session</p><h2 className="mt-3 max-w-3xl text-3xl font-black sm:text-4xl">How This Reflex Test Measures Your Response</h2><p className="mt-5 max-w-4xl leading-7 text-slate-600">A useful reflex test needs more than a stopwatch. It must make the signal unpredictable, reject early responses, and collect enough valid attempts to reduce the effect of one unusual click. This tester introduces a random wait before each green signal and discards false starts. After five valid rounds, it calculates an average and identifies the fastest response.</p><p className="mt-4 max-w-4xl leading-7 text-slate-600">The reported number covers the complete browser measurement chain. It begins when the interface changes state and ends when the browser receives your input. It cannot separate neural processing from monitor refresh, operating-system scheduling, and switch or touchscreen delay. That is why a controlled setup and repeated personal comparison are more useful than claiming an absolute biological reflex time.</p><div className="mt-12 grid gap-10 md:grid-cols-3"><section><p className="data-number text-sm font-black text-action">01 · DETECT</p><h3 className="mt-3 text-xl font-black">See the signal clearly</h3><p className="mt-3 leading-7 text-slate-600">Look near the center of the panel without staring at a single letter or trying to count the delay. The full surface changes color, which makes the cue usable on both desktop and mobile. Brightness, contrast, display refresh rate, and visual attention can still influence when the signal reaches you.</p></section><section><p className="data-number text-sm font-black text-signal">02 · RESPOND</p><h3 className="mt-3 text-xl font-black">Use one consistent input</h3><p className="mt-3 leading-7 text-slate-600">Click, tap, or use the keyboard after green appears. A mouse switch, trackpad, touchscreen, and keyboard have different mechanical and processing delays. Pick one input method for a comparison series. Switching devices between attempts makes it difficult to know whether you changed or the hardware did.</p></section><section><p className="data-number text-sm font-black text-caution">03 · COMPARE</p><h3 className="mt-3 text-xl font-black">Judge the session, not one round</h3><p className="mt-3 leading-7 text-slate-600">Your best attempt shows peak speed, but the average is the better baseline. Also notice the range between attempts. A compact cluster suggests stable attention, while one very slow response may reflect a momentary distraction. Repeat on another day before deciding that your reflex speed has changed.</p></section></div></div></section>

        <section className="copy-section border-b border-line bg-paper py-16 sm:py-24"><div className="mx-auto grid max-w-6xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.85fr_1.15fr] lg:gap-20"><div><p className="text-xs font-black uppercase tracking-[0.1em] text-action">Fair comparison</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Common Reflex Tester Mistakes</h2><p className="mt-5 leading-7 text-slate-600">The most common error is predicting the green signal instead of reacting to it. A result achieved by guessing is not a faster reflex. Repeated false starts are a sign to pause, relax your hand, and restart the set.</p><p className="mt-4 leading-7 text-slate-600">Another mistake is comparing unlike tasks. An audio cue, a falling ruler, a color-choice game, and this visual reflex game involve different sensory and decision steps. Use one test protocol when tracking progress.</p><h3 className="mt-8 text-xl font-black">Reflexes in games and sports</h3><p className="mt-3 leading-7 text-slate-600">Fast responses are one ingredient in a game or sport, but anticipation, pattern recognition, positioning, decision quality, and movement accuracy often matter just as much. A goalkeeper can move early because they read a shot, while a player who waits for the ball may need a faster raw response. Treat this page as a focused warm-up and benchmark, not a prediction of match performance.</p></div><div><h3 className="text-2xl font-black">Before your next five rounds</h3><ul className="mt-6 divide-y divide-line border-y border-line text-sm leading-6 text-slate-600"><li className="py-4"><strong className="text-ink">Close busy tabs:</strong> background work can interrupt browser timing and distract your attention.</li><li className="py-4"><strong className="text-ink">Keep the tab visible:</strong> switching apps invalidates an active round and makes the session inconsistent.</li><li className="py-4"><strong className="text-ink">Use a stable position:</strong> keep your hand ready but relaxed instead of changing posture between rounds.</li><li className="py-4"><strong className="text-ink">Avoid marathon testing:</strong> fatigue and task familiarity can pull scores in different directions.</li><li className="py-4"><strong className="text-ink">Record the setup:</strong> note whether you used a phone, touchscreen, trackpad, or wired mouse.</li></ul></div></div></section>

        <section id="faq" className="faq copy-section bg-paper py-16 sm:py-24"><div className="mx-auto grid max-w-6xl gap-10 px-4 sm:px-6 lg:grid-cols-[0.65fr_1.35fr] lg:gap-20"><div><p className="text-xs font-black uppercase tracking-[0.1em] text-action">Quick answers</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Reflex Test FAQ</h2><p className="mt-5 text-sm leading-6 text-slate-600">How the reflex tester works and how to compare scores.</p></div><div className="border-t border-line">{faqItems.map(([question, answer]) => <details className="group border-b border-line py-5" key={question}><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-bold"><span>{question}</span><Plus aria-hidden="true" className="faq-plus h-5 w-5 shrink-0 text-action transition-transform" /></summary><p className="mt-4 max-w-3xl text-sm leading-6 text-slate-600">{answer}</p></details>)}</div></div></section>

        <section className="copy-section border-t border-line bg-white py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="text-xl font-black">Testing Method</h2><p className="mt-4 max-w-4xl text-sm leading-6 text-slate-600">The timer starts when the interface enters its green state and ends on pointer or keyboard activation using <code className="rounded bg-paper px-1 py-0.5">performance.now()</code>. Background-tab interruptions invalidate the active round. This browser tool is for personal comparison and entertainment, not medical assessment.</p><a href="https://doi.org/10.3389/fnhum.2015.00131" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-action">Read reaction-time research <ExternalLink aria-hidden="true" className="h-4 w-4" /></a></div></section>
      </article></main>
      <footer className="border-t border-line bg-ink py-10 text-white"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-4 sm:px-6 md:flex-row md:items-end md:justify-between"><div><a href="/" className="font-black uppercase text-white no-underline">Reaction Time</a><p className="mt-2 text-xs text-slate-400">A free browser-based reflex and reaction test. Not a medical assessment.</p></div><p className="text-xs text-slate-500">© {new Date().getFullYear()} reaction-test.org</p></div></footer>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    </>
  );
}
